name: KiCad Project Automation

on: [push]

jobs:
  Check-Files:
    name: Check Files
    runs-on: ubuntu-latest
    outputs:
      pcb_change: ${{ steps.check_files.outputs.pcb_change }}
    steps:
      - name: Checkout repository (branch 42)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: 42

      - name: Check if kicad_pcb was modified
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^mC3.kicad_pcb$"; then
            echo "pcb_change=true" >> $GITHUB_ENV
            echo "pcb_change=true" >> $GITHUB_OUTPUT
          else
            echo "pcb_change=false" >> $GITHUB_ENV
            echo "pcb_change=false" >> $GITHUB_OUTPUT
          fi

  Compressing:
    name: Compress Files
    runs-on: ubuntu-latest
    needs: [Check-Files]
    steps:
      - name: Checkout repository (branch 42)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 42

      - name: Get current date and time
        id: datetime
        run: echo "timestamp=42-$(date +'%d%m%y%H%M')" >> $GITHUB_ENV

      - name: Create ZIP archive (outside Archive folder)
        run: zip "mC3-${{ env.timestamp }}.zip" mC3.kicad_pcb mC3.kicad_prl mC3.kicad_pro mC3.kicad_sch

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Remove old ZIP file
        run: |
          rm -f Archive/mC3-42-*.zip || true

      - name: Move ZIP file to main branch
        run: |
          mkdir -p Archive
          mv "mC3-${{ env.timestamp }}.zip" Archive/

      - name: Commit and Push changes to main branch
        run: |
          git add Archive/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update archive: mC3-${{ env.timestamp }} from branch 42"
          git push origin main

  Export-Files:
    name: Export Schematic PDF & BOM
    runs-on: ubuntu-latest
    needs: [Move-Files]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install --yes kicad-cli

      - name: Export Schematic PDF
        run: |
          mkdir -p Exports
          kicad-cli sch export pdf -o Exports/mC3-schematic.pdf mC3.kicad_sch

      - name: Export Bill of Materials (BOM)
        run: |
          kicad-cli sch export bom -o Exports/mC3-bom.csv mC3.kicad_sch

      - name: Commit and Push Exported Files
        run: |
          git add Exports/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Export Schematic PDF and BOM"
          git push origin main