name: KiCad Project Automation

on:
  push:
    branches:
      - '17048'
    paths:
      - 'Caps32Project.kicad_pcb'
      - 'Caps32Project.kicad_prl'
      - 'Caps32Project.kicad_pro'
      - 'Caps32Project.kicad_sch'

jobs:
  Compressing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (branch 17048)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 17048

      - name: Get current date and time
        id: datetime
        run: echo "timestamp=17048-$(date +'%d%m%y%H%M')" >> $GITHUB_ENV

      - name: Create ZIP archive (outside Archive folder)
        run: zip "Caps32Project-${{ env.timestamp }}.zip" Caps32Project.kicad_pcb Caps32Project.kicad_prl Caps32Project.kicad_pro Caps32Project.kicad_sch

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Remove old ZIP file
        run: |
          rm -f Archive/Caps32Project-17048-*.zip || true

      - name: Move ZIP file to main branch
        run: |
          mkdir -p Archive
          mv "Caps32Project-${{ env.timestamp }}.zip" Archive/

      - name: Commit and Push changes to main branch
        run: |
          git add Archive/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update archive: Caps32Project-${{ env.timestamp }} from branch 17048"
          git push origin main

  Render-Images:
    name: PCB Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 17048
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: "17048"

      - name: Check if only kicad_pcb was modified
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^Caps32Project.kicad_pcb$"; then
            echo "run_render=true" >> $GITHUB_ENV
          else
            echo "run_render=false" >> $GITHUB_ENV
          fi

      - name: Render PCB Images
        if: env.run_render == 'true'
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          
      - name: Render PCB GIF
        if: env.run_render == 'true'
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          animation: gif

      - name: Commit and Push Rendered Images
        if: env.run_render == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images
          git commit -m "Update PCB render images"
          git push origin 17048

  Move-Files:
    name: Move to Main
    runs-on: ubuntu-latest
    needs: Render-Images
    steps:
      - name: Checkout branch 17048
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: "17048"

      - name: Check if only kicad_pcb was modified
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^Caps32Project.kicad_pcb$"; then
            echo "run_move=true" >> $GITHUB_ENV
          else
            echo "run_move=false" >> $GITHUB_ENV
          fi

      - name: Checkout main branch
        if: env.run_move == 'true'
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: main-branch

      - name: Move images to main branch
        if: env.run_move == 'true'
        run: |
          mkdir -p main-branch/Images/17048
          mv images/bottom.png main-branch/Images/17048/ 2>/dev/null || true
          mv images/rotating.gif main-branch/Images/17048/ 2>/dev/null || true
          mv images/top.png main-branch/Images/17048/ 2>/dev/null || true

      - name: Commit and push changes to main
        if: env.run_move == 'true'
        run: |
          cd main-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Images/17048
          git commit -m "Update images: Rendered files 17048"
          git push origin main

      - name: Delete images folder from branch 17048
        if: env.run_move == 'true'
        run: |
          git checkout 17048
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -rf images
          rm -rf main-branch
          git add .
          git commit -m "Remove images folder after moving to main" || true
          git push origin 17048
