name: Compress KiCad Files
on:
  push:
    branches:
      - '340'
    paths:
      - 'Caps32Project.kicad_pcb'
      - 'Caps32Project.kicad_prl'
      - 'Caps32Project.kicad_pro'
      - 'Caps32Project.kicad_sch'
jobs:
  Compressing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (branch 340)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 340

      - name: Get current date and time
        id: datetime
        run: echo "timestamp=340-$(date +'%d%m%y%H%M')" >> $GITHUB_ENV

      - name: Create ZIP archive (outside Archive folder)
        run: zip "Caps32Project-${{ env.timestamp }}.zip" Caps32Project.kicad_pcb Caps32Project.kicad_prl Caps32Project.kicad_pro Caps32Project.kicad_sch

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Remove old ZIP file
        run: |
          rm -f Archive/Caps32Project-340-*.zip || true

      - name: Move ZIP file to main branch
        run: |
          mkdir -p Archive
          mv "Caps32Project-${{ env.timestamp }}.zip" Archive/

      - name: Commit and Push changes to main branch
        run: |
          git add Archive/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update archive: Caps32Project-${{ env.timestamp }} from branch 340"
          git push origin main

  Check-Changes:
    runs-on: ubuntu-latest
    outputs:
      PCB: ${{ steps.check.outputs.PCB }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
    - name: Check if PCB File Changed
      id: check
      run: |
        # Pastikan ada minimal 2 commit sebelum melakukan git diff
        if [ $(git log --oneline | wc -l) -lt 2 ]; then
          echo "PCB=false" >> "$GITHUB_ENV"
          echo "PCB=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Jika ada lebih dari 1 commit, jalankan git diff
        if git diff --name-only HEAD~1 HEAD | grep -q "Caps32Project.kicad_pcb"; then
          echo "PCB=true" >> "$GITHUB_ENV"
          echo "PCB=true" >> "$GITHUB_OUTPUT"
        else
          echo "PCB=false" >> "$GITHUB_ENV"
          echo "PCB=false" >> "$GITHUB_OUTPUT"
        fi

  Render-Images:
    name: PCB Render
    runs-on: ubuntu-latest
    needs: [Compressing, Check-Changes]
    if: needs.Check-Changes.outputs.PCB == 'true'
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          animation: gif

      - name: Commit and Push Rendered Images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images
          git commit -m "Update PCB render images"
          git push origin 340

  Move-Files:
    name: Move Rendered Images to Main
    runs-on: ubuntu-latest
    needs: Render-Images
    steps:
      - name: Checkout branch 340
        uses: actions/checkout@v4
        with:
          ref: "340"

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: main-branch

      - name: Move images to main branch
        run: |
          mkdir -p main-branch/Images/340
          mv images/bottom.png main-branch/Images/340/ 2>/dev/null || true
          mv images/rotating.gif main-branch/Images/340/ 2>/dev/null || true
          mv images/top.png main-branch/Images/340/ 2>/dev/null || true

      - name: Commit and push changes to main
        run: |
          cd main-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Images/340
          git commit -m "Update images: Rendered files"
          git push origin main

      - name: Delete images folder from branch 340
        run: |
          git checkout 340
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -rf images
          rm -rf main-branch
          git add .
          git commit -m "Remove images folder after moving to main" || true
          git push origin 340
