name: images
on:
  push:

jobs:
  render-images:
    name: PCB Render for ${{ matrix.branch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [42, 17048, 340]

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/${{ matrix.branch }}
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/${{ matrix.branch }}
          animation: gif

      - name: Commit and Push Changes to index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout index
          git add images/${{ matrix.branch }}
          git commit -m "Update PCB render images for branch ${{ matrix.branch }}"
          git push origin index
        continue-on-error: true