name: Images Render
on:
  push:
    branches:
      - '42'
    paths:
      - 'Caps32Project.kicad_pcb'
  workflow_dispatch:
jobs:
  render-images:
    name: PCB Render
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          animation: gif

      - name: Commit and Push Branch 42
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images
          git commit -m "Update PCB render images"
          git push origin 42

      - name: Copy Files from 42 to main/42
        run: |
          git checkout 42 -- \
            bottom.png \
            rotating.gif \
            top.png || echo "Warning: Some files might not exist in branch 42"
  
          mv checkout 42 -- \
             bottom.png \
             rotating.gif \
             main_branch/Images/42/ || echo "Warning: Some files might not exist, skipping move."

      - name: Commit and Push Changes to Main
        run: |
          cd main_branch
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          git diff --staged --quiet || git commit -m "Sync from 42 to main/42"

      - name: Remove 'images' Folder from Branch 42
        run: |
          # Checkout branch 42 again
          git checkout 42
          
          # Remove the images folder in branch 42
          rm -rf images
          git add .  # Stage the removal
          git commit -m "Remove images folder after moving to main"
          git push origin 42