name: images
on:
  push:

jobs:
  render-images-42:
    name: PCB Render for 42
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Branch 42
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 42

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/42
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/42
          animation: gif

      - name: Commit and Push Changes to index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout index
          git add images/42
          git commit -m "Update PCB render images for branch 42"
          git push origin index
        continue-on-error: true

  render-images-17048:
    name: PCB Render for 17048
    runs-on: ubuntu-latest
    needs: render-images-42  # Menunggu job 42 selesai terlebih dahulu
    steps:
      - name: Check Out Branch 17048
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 17048

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/17048
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/17048
          animation: gif

      - name: Commit and Push Changes to index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout index
          git add images/17048
          git commit -m "Update PCB render images for branch 17048"
          git push origin index
        continue-on-error: true

  render-images-340:
    name: PCB Render for 340
    runs-on: ubuntu-latest
    needs: render-images-17048  # Menunggu job 17048 selesai terlebih dahulu
    steps:
      - name: Check Out Branch 340
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 340

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/340
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images/340
          animation: gif

      - name: Commit and Push Changes to index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout index
          git add images/340
          git commit -m "Update PCB render images for branch 340"
          git push origin index
        continue-on-error: true