name: images
on:
  push:
    branches:
      - '42'
jobs:
  render-images:
    name: render-images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Mengambil seluruh riwayat repo untuk checkout branch

      - name: render pcb images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          
      - name: render pcb gif
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          animation: gif

      - name: Commit and Push to main
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git pull origin main  # Pastikan branch main terbaru sebelum commit
          git add images/
          git diff --staged --quiet || git commit -m 'Add rendered PCB images and GIFs'
          git push origin main

      - name: Setup Pages
        if: github.ref == 'refs/heads/42'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/42'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "images"

  deploy-pages:
    if: github.ref == 'refs/heads/42'
    runs-on: ubuntu-latest
    needs: render-images
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
