name: Images Rendering
on:
  workflow_run:
    workflows: ["Compress KiCad Files"]
    types:
      - completed
  push:
    branches:
      - "702"
    paths:
      - "Caps32Project.kicad_pcb"
jobs:
  Render-Images:
    name: PCB Render
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          
      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: Caps32Project.kicad_pcb
          output_path: ${{ github.workspace }}/images
          animation: gif

      - name: Commit and Push Rendered Images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images
          git commit -m "Update PCB render images"
          git push origin 702

  Move-Files:
    name: Move to Main
    runs-on: ubuntu-latest
    needs: Render-Images
    steps:
      - name: Checkout branch 702
        uses: actions/checkout@v4
        with:
          ref: "702"

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: main-branch

      - name: Move images to main branch
        run: |
          mkdir -p main-branch/Images/702
          mv images/bottom.png main-branch/Images/702/ 2>/dev/null || true
          mv images/rotating.gif main-branch/Images/702/ 2>/dev/null || true
          mv images/top.png main-branch/Images/702/ 2>/dev/null || true

      - name: Commit and push changes to main
        run: |
          cd main-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Images/702
          git commit -m "Update images: Rendered files"
          git push origin main

      - name: Delete images folder from branch 702
        run: |
          git checkout 702
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -rf images
          rm -rf main-branch
          git add .
          git commit -m "Remove images folder after moving to main" || true
          git push origin 702
