name: Sync
on:
  push:
    branches:
      - '42'
      - '17048'
      - '340'
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current branch name
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Copy to main/${{ env.BRANCH_NAME }}
        run: |
          git checkout main
          git pull origin main
          mkdir -p ${{ env.BRANCH_NAME }}

          git checkout ${{ env.BRANCH_NAME }} -- \
            Caps32Project.kicad_pcb \
            Caps32Project.kicad_plr \
            Caps32Project.kicad_pro \
            Caps32Project.kicad_sch \
            fp-info-cache

          cp -r Caps32Project.kicad_pcb Caps32Project.kicad_plr \
                Caps32Project.kicad_pro Caps32Project.kicad_sch \
                fp-info-cache \
                ${{ env.BRANCH_NAME }}/

          git add .
          git diff --staged --quiet || git commit -m "Sync from ${{ env.BRANCH_NAME }} to main/${{ env.BRANCH_NAME }}"
        
      - name: Push changes to main
        run: |
          git push origin main